export enum POSITION_ENUM {
  TOPING = "TOPING",
  RECOMMEND_PRODUCTS = "RECOMMEND_PRODUCTS",
  COMPLETED_MASTERPIECES = "COMPLETED_MASTERPIECES",
  FASTEST_GROWING = "FASTEST_GROWING",
  TESTING_NEW_PRODUCTS = "TESTING_NEW_PRODUCTS",
}